### ISSUE TITLE
How do you make it work?

### ISSUE THREAD

**Issue by Lucindiee** [Liverus/Metamorph#1]
![image](https://github.com/Liverus/Metamorph/assets/160425575/e6817fa5-4033-4be5-b1f8-087987558a8a)
when i open the .exe this is what i get. how do i get the spoofer to work?

**Comment by Liverus** [comment]
It has the same requirements as kdmapper, https://github.com/TheCruZ/kdmapper?tab=readme-ov-file#error-0xc0000603
