### ISSUE TITLE
its a issue

### ISSUE THREAD

**Issue by jason3423413** [Liverus/Metamorph#2]
![Screenshot 2024-02-19 094431](https://github.com/Liverus/Metamorph/assets/160530605/a82cb10f-b5f1-450f-9640-1b471cc70dd8)

**Comment by jason3423413** [comment]
is there any requirements to use this cheats if so what are they so I can add them to my PC

**Comment by Liverus** [comment]
https://github.com/Liverus/Metamorph/issues/1#issuecomment-1951438581

**Comment by jason3423413** [comment]
can you make a tutorial on how to fix it

**Comment by Liverus** [comment]
Everything is explained in the microsoft post
